version: "3"
services:
  web:
    restart: on-failure:10
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    #command: newrelic-admin run-program gunicorn appointmentguru.wsgi:application -b :8000 --reload
    volumes:
      - .:/code
    ports:
      - "8001:8000"

volumes:
  postgres-db-volume:
